FORMAT: 1A
HOST: http://37.230.102.31

# KentekenAPI
KentekenAPI geeft de beschikbare RDW informatie terug behorend bij een bepaald kenteken.

## Kentekens [/KentekenAPI/kentekens/{kenteken}]
Alle informatie behorende bij een kenteken.

+ Parameters
    + kenteken (required, string, `70rpjj`) ... Het `kenteken` van het betreffende voertuig.

### Haal kenteken op [GET]
+ Response 200 (application/json)

    + Body

            {
                "@context": {
                    "vso": "http://purl.org/vso/ns#",
                    "xsd": "http://www.w3.org/2001/XMLSchema#",
                    "Aantalzitplaatsen": {
                        "@id":"vso:seatingCapacity",
                        "@type":"xsd:integer"
                    }
                },
                "success" : true,
                "resource" : {
                    "Aantalcilinders" : 4,
                    "Aantalstaanplaatsen" : null,
                    "Aantalzitplaatsen" : 5,
                    "BPM" : 3082,
                    "Brandstofverbruikbuitenweg" : 5.00,
                    "Brandstofverbruikgecombineerd" : 6.30,
                    "Brandstofverbruikstad" : 8.40,
                    "Catalogusprijs" : 15250,
                    "Cilinderinhoud" : 1360,
                    "CO2uitstootgecombineerd" : 149,
                    "Datumaanvangtenaamstelling" : "2013-04-04T00:00:00",
                    "DatumeersteafgifteNederland" : "2005-07-20T00:00:00",
                    "Datumeerstetoelating" : "2005-07-20T00:00:00",
                    "Eerstekleur" : "ROOD",
                    "G3installatie" : "N.v.t.",
                    "Handelsbenaming" : "206; 1.4 3DRS",
                    "Hoofdbrandstof" : "Benzine",
                    "Inrichting" : "hatchback",
                    "Kenteken" : "70RPJJ",
                    "Laadvermogen" : null,
                    "Massaleegvoertuig" : 925,
                    "Massarijklaar" : 1025,
                    "Maximaleconstructiesnelheid" : null,
                    "Maximumtetrekkenmassaautonoomgeremd" : null,
                    "Maximumtetrekkenmassageremd" : 1100,
                    "Maximumtetrekkenmassamiddenasgeremd" : null,
                    "Maximumtetrekkenmassaongeremd" : 510,
                    "Maximumtetrekkenmassaopleggergeremd" : null,
                    "Merk" : "PEUGEOT",
                    "Milieuclassificatie" : "Niet geregistreerd",
                    "Nevenbrandstof" : "Niet geregistreerd",
                    "Retrofitroetfilter" : false,
                    "Toegestanemaximummassavoertuig" : 1450,
                    "Tweedekleur" : "Niet geregistreerd",
                    "Vermogen" : 55,
                    "Vermogenbromsnorfiets" : null,
                    "VervaldatumAPK" : "2014-04-02T00:00:00",
                    "Voertuigsoort" : "Personenauto",
                    "Wachtopkeuren" : false,
                    "WAMverzekerdgeregistreerd" : true,
                    "Zuinigheidslabel" : "C"
                }
            }