FORMAT: 1A
HOST: http://37.230.102.31

# KentekenAPI
KentekenAPI geeft de beschikbare RDW informatie terug behorend bij een bepaald kenteken.

## Kentekens [/KentekenAPI/kentekens/{kenteken}]
Alle informatie behorende bij een kenteken.

+ Parameters
    + kenteken (required, string, `70rpjj`) ... Het `kenteken` van het betreffende voertuig.

### Haal kenteken op [GET]
+ Response 200 (application/json)

    + Body

            {
                "@context": {
                    "@language": "nl",
                    "foaf": "http://xmlns.com/foaf/0.1/",
                    "rdwv": "https://w3id.org/rdw/vehicles#",
                    "dbpedia": "http://dbpedia.org/resource/",
                    "label": "http://www.w3.org/2000/01/rdf-schema#label",
                    "resource": "foaf:topic",
                    "Aantalcilinders": {
                        "@id": "rdwv:numberOfCylinders",
                        "@type": "xsd:integer"
                    },
                    "Aantalstaanplaatsen": {
                        "@id": "rdwv:numberOfStandingPlaces",
                        "@type": "xsd:integer"
                    },
                    "Aantalzitplaatsen": {
                        "@id": "rdwv:numberOfSeats",
                        "@type": "xsd:integer"
                    },
                    "BPM": {
                        "@id": "rdwv:bpm",
                        "@type": "xsd:integer"
                    },
                    "Brandstofverbruikbuitenweg": {
                        "@id": "rdwv:fuelConsumptionExtraUrban",
                        "@type": "xsd:double"
                    },
                    "Brandstofverbruikgecombineerd": {
                        "@id": "rdwv:fuelConsumptionCombined",
                        "@type": "xsd:double"
                    },
                    "Brandstofverbruikstad": {
                        "@id": "rdwv:fuelConsumptionUrban",
                        "@type": "xsd:double"
                    },
                    "Catalogusprijs": {
                        "@id": "rdwv:catalogPrice",
                        "@type": "xsd:integer"
                    },
                    "Cilinderinhoud": {
                        "@id": "rdwv:cylinderCapacity",
                        "@type": "xsd:integer"
                    },
                    "CO2uitstootgecombineerd": {
                        "@id": "rdwv:co2EmissionCombined",
                        "@type": "xsd:integer"
                    },
                    "Datumaanvangtenaamstelling": {
                        "@id": "rdwv:registrationCommencementDate",
                        "@type": "xsd:dateTime"
                    },
                    "DatumeersteafgifteNederland": {
                        "@id": "rdwv:initialRegistrationDateNetherlands",
                        "@type": "xsd:dateTime"
                    },
                    "Datumeerstetoelating": {
                        "@id": "rdwv:initialRegistrationDate",
                        "@type": "xsd:dateTime"
                    },
                    "Eerstekleur": {
                        "@id": "rdwv:firstColor",
                        "@type": "@id"
                    },
                    "G3installatie": {
                        "@id": "rdwv:g3Installation",
                        "@type": "@id"
                    },
                    "Handelsbenaming": {
                        "@id": "rdwv:tradeDesignation",
                        "@type": "xsd:string"
                    },
                    "Hoofdbrandstof": {
                        "@id": "rdwv:primaryFuel",
                        "@type": "@id"
                    },
                    "Inrichting": {
                        "@id": "rdwv:bodyStyle",
                        "@type": "@id"
                    },
                    "Kenteken": {
                        "@id": "rdwv:registration",
                        "@type": "xsd:string"
                    },
                    "Laadvermogen": {
                        "@id": "rdwv:loadCapacity",
                        "@type": "xsd:integer"
                    },
                    "Massaleegvoertuig": {
                        "@id": "rdwv:emptyVehicleMass",
                        "@type": "xsd:integer"
                    },
                    "Massarijklaar": {
                        "@id": "rdwv:kerbMass",
                        "@type": "xsd:integer"
                    },
                    "Maximaleconstructiesnelheid": {
                        "@id": "rdwv:maximumConstructionSpeed",
                        "@type": "xsd:integer"
                    },
                    "Maximumtetrekkenmassaautonoomgeremd": {
                        "@id": "rdwv:maximumAutonomousBrakedTowMass",
                        "@type": "xsd:integer"
                    },
                    "Maximumtetrekkenmassageremd": {
                        "@id": "rdwv:maximumBrakedTowMass",
                        "@type": "xsd:integer"
                    },
                    "Maximumtetrekkenmassamiddenasgeremd": {
                        "@id": "rdwv:maximumMidAxleBrakedTowMass",
                        "@type": "xsd:integer"
                    },
                    "Maximumtetrekkenmassaongeremd": {
                        "@id": "rdwv:maximumUnbrakedTowMass",
                        "@type": "xsd:integer"
                    },
                    "Maximumtetrekkenmassaopleggergeremd": {
                        "@id": "rdwv:maximumBrakedSemitrailerTowMass",
                        "@type": "xsd:integer"
                    },
                    "Merk": {
                        "@id": "rdwv:brand",
                        "@type": "@id"
                    },
                    "Milieuclassificatie": {
                        "@id": "rdwv:environmentalClassification",
                        "@type": "@id"
                    },
                    "Nevenbrandstof": {
                        "@id": "rdwv:secondaryFuel",
                        "@type": "xsd:string"
                    },
                    "Retrofitroetfilter": {
                        "@id": "rdwv:retrofitDieselParticulateFilter",
                        "@type": "xsd:boolean"
                    },
                    "Toegestanemaximummassavoertuig": {
                        "@id": "rdwv:maximumPermissibleVehicleMass",
                        "@type": "xsd:integer"
                    },
                    "Tweedekleur": {
                        "@id": "rdwv:secondColor",
                        "@type": "@id"
                    },
                    "Vermogen": {
                        "@id": "rdwv:power",
                        "@type": "xsd:integer"
                    },
                    "Vermogenbromsnorfiets": {
                        "@id": "rdwv:powerMoped",
                        "@type": "xsd:string"
                    },
                    "VervaldatumAPK": {
                        "@id": "rdwv:expiryDateAPK",
                        "@type": "xsd:dateTime"
                    },
                    "Voertuigsoort": {
                        "@id": "rdf:type",
                        "@type": "@id"
                    },
                    "Wachtopkeuren": {
                        "@id": "rdwv:waitingForApproval",
                        "@type": "xsd:boolean"
                    },
                    "WAMverzekerdgeregistreerd": {
                        "@id": "rdwv:wamInsuranceRegistered",
                        "@type": "xsd:boolean"
                    },
                    "Zuinigheidslabel": {
                        "@id": "rdwv:efficiencyLabel",
                        "@type": "@id"
                    }
                },
                "@id": "",
                "success" : true,
                "resource" : {
                    "@id": "#this",
                    "Aantalcilinders" : 4,
                    "Aantalstaanplaatsen" : null,
                    "Aantalzitplaatsen" : 5,
                    "BPM" : 3082,
                    "Brandstofverbruikbuitenweg" : 5.00,
                    "Brandstofverbruikgecombineerd" : 6.30,
                    "Brandstofverbruikstad" : 8.40,
                    "Catalogusprijs" : 15250,
                    "Cilinderinhoud" : 1360,
                    "CO2uitstootgecombineerd" : 149,
                    "Datumaanvangtenaamstelling" : "2013-04-04T00:00:00",
                    "DatumeersteafgifteNederland" : "2005-07-20T00:00:00",
                    "Datumeerstetoelating" : "2005-07-20T00:00:00",
                    "Eerstekleur" : {
                        "@id" : "rdwv:Red",
                        "label" : "Rood"
                    },
                    "G3installatie" : null,
                    "Handelsbenaming" : "206; 1.4 3DRS",
                    "Hoofdbrandstof" : {
                        "@id": "rdwv:Benzine",
                        "label": "Benzine"
                    },
                    "Inrichting" : {
                        "@id": "dbpedia:Hatchback",
                        "label": "Hatchback"
                    },
                    "Kenteken" : "70RPJJ",
                    "Laadvermogen" : null,
                    "Massaleegvoertuig" : 925,
                    "Massarijklaar" : 1025,
                    "Maximaleconstructiesnelheid" : null,
                    "Maximumtetrekkenmassaautonoomgeremd" : null,
                    "Maximumtetrekkenmassageremd" : 1100,
                    "Maximumtetrekkenmassamiddenasgeremd" : null,
                    "Maximumtetrekkenmassaongeremd" : 510,
                    "Maximumtetrekkenmassaopleggergeremd" : null,
                    "Merk" : {
                        "@id" : "dbpedia:Peugeot",
                        "label" : "Peugeot"
                    },
                    "Milieuclassificatie" : null,
                    "Nevenbrandstof" : null,
                    "Retrofitroetfilter" : false,
                    "Toegestanemaximummassavoertuig" : 1450,
                    "Tweedekleur" : null,
                    "Vermogen" : 55,
                    "Vermogenbromsnorfiets" : null,
                    "VervaldatumAPK" : "2014-04-02T00:00:00",
                    "Voertuigsoort" : {
                        "@id": "rdwv:PassengerVehicle",
                        "label": "Personenauto"
                    },
                    "Wachtopkeuren" : false,
                    "WAMverzekerdgeregistreerd" : true,
                    "Zuinigheidslabel" : {
                        "@id": "rdwv:EfficiencyLabelC",
                        "label": "C"
                    }
                }
            }
